### ISSUE TITLE
matchmaking

### ISSUE THREAD

**Issue by ycenta** [ESGI-69/challenge-node-vue#29]
Un mec qui a fait une lib de match making, elle est toute simple https://github.com/cestef/gamemaker/blob/main/src/matchMaker.js et elle peut etre enrichi avec les events node js https://nodejs.dev/fr/learn/the-nodejs-event-emitter/

**Comment by mrpinkcat** [comment]
On va pas faire de match making, on va plutôt faire un système d'invitation ou de room avec un code. Vue a la vitesse à la quelle on avance, on a pas temps
